#!/bin/sh
#
# Called by "git commit" with no arguments.
#

set -e

# --- Safety check
if [ -z "${GIT_DIR}" ]; then
	echo "Don't run this script from the command line." >&2
	echo " (if you want, you could supply GIT_DIR)" >&2
	exit 1
fi

HOOKS_DIR=${HOOKS_DIR:-${GIT_DIR}/hooks}

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

tmp_diff_file=$(mktemp)

finish() {
	rm -f ${tmp_diff_file}
}
trap finish EXIT

LC_ALL=C git diff --cached $against -- > ${tmp_diff_file}
${HOOKS_DIR}/check-diff.py ${tmp_diff_file}
