name: Commit-checker

on:
  pull_request:
    branches:
      - master

jobs:
  commit-checker:
    name: Commit checker

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Rebase to ${{ github.base_ref }} branch
      run: |
        git config user.email 'info@openttd.org'
        git config user.name 'OpenTTD CI'
        git rebase origin/$GITHUB_BASE_REF
    - name: Check commits
      uses: ./
